include: package:yumemi_lints/flutter/3.22/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
  errors:
    invalid_annotation_target: ignore